### PR TITLE
Bump capistrano to latest version to avoid OpenSSL error

### PR DESCRIPTION
**Pull request by agaelebe**
Capistrano 3.4 doesn't work with Ruby 2.4 and later due to a change in OpenSSL api (undefined method `p=' for <OpenSSL::PKey).
I'm using 3.11 version on my deploy without any issues.

### CODE REVIEW

**Comment by dsander** [comment]
Thanks! @cantino can you confirm it is still working for you?

**Comment by cantino** [comment]
I switched to Docker a few months ago ;)

**Comment by dsander** [comment]
Oh ok, If it works for @agaelebe it will probably work for everyone 😄
